version: "3.9"
services:
  clevertap:
    container_name: clevertap_events
    build:
      context: .
      dockerfile: deployment/dockerfile/clevertap.Dockerfile
    image: clevertap_events
    ports:
      - "8012:8012"
    environment:
      - ENCR_MONGO_URL=mongodb+srv://manish:KlSh0bX605PY509h@cluster0.ebwdr.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      - DB_NAME=test
      - COLLECTION_NAME=clevertap
      - PORT=8012
      - HOST=0.0.0.0
      - AWS_ACCESS_KEY_ID=AKIAWA2LKV64N6ADAGNO
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=ap-south-1
      - PYTHONUNBUFFERED=1
      - CLEVERTAP_CX_APP_ACCOUNT_ID = "4RW-KZK-995Z"
      - CLEVERTAP_CX_APP_PASSCODE = "AOW-ROB-WXKL"
      - CLEVERTAP_CL_APP_ACCOUNT_ID = "867-RZK-995Z"
      - CLEVERTAP_CL_APP_PASSCODE = "SMQ-IOB-WXKL"
      - CLEVERTAP_CX_ACCOUNT_ID = "4RW-KZK-995Z"
      - CLEVERTAP_CX_PASSCODE = "AOW-ROB-WXKL"
    deploy:
      resources:
        limits:
          memory: 2048M