version: "3.9"
services:
  web_01:
    build: .
    ports:
      - "8010:8010"
    environment:
      - ENCR_MONGO_URL=mongodb+srv://manish:KlSh0bX605PY509h@cluster0.ebwdr.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      - DB_NAME=test
      - COLLECTION_NAME=test
      - LOG_MONGO_URL=mongodb+srv://manish:KlSh0bX605PY509h@cluster0.ebwdr.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      - LOG_DB_NAME=test
      - LOG_COLLECTION_NAME=test
      - PORT=8010
      - HOST=0.0.0.0
      - AWS_ACCESS_KEY_ID=AKIA3RSHCMQMTLUCYGU2
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=ap-south-1
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          memory: 2048M

