CLEVERTAP_CX_ACCOUNT_ID = "4RW-KZK-995Z"
CLEVERTAP_CX_PASSCODE = "AOW-ROB-WXKL"

cx_app_event_names = [
    'Notification Clicked', 
    'Notification Delivered', 
    'Notification Replied', 
    'Notification Viewed', 
    'UTM Visited  Address not serviceable', 
    'Address Submit', 
    'App Launched Custom', 
    'Apply Coupon', 
    'Bottom Tab', 
    'Checkout Started', 
    'Coupon Applied', 
    'Coupon Selected', 
    'Cx Referral', 
    'Cx Referral Landing', 
    'GB Charged', 
    'GB Product Added', 
    'GB Share', 
    'List Share', 
    'List Viewed Cat Nav', 
    'Product Clicked', 
    'Product List Viewed', 
    'Product Share', 
    'Successful Registration', 
    'Successful Login  WA Status Banner Click  WA Status Save Number', 
    'WA Status Success', 
    'Session Concluded', 
    'Payment Mode Selected', 
    'KJ Landing', 
    'KJ Spin Clicked', 
    'KJ Past SC Landing', 
    'KJ Past SC Clicked', 
    'KJ SC Landing', 
    'KJ Scratched', 
    'Story Clicked', 
    'Story Viewed', 
    'KJ SC Coupon_Copy', 
    'Story Shared', 
    'FD PDU Clicked', 
    'FD PDP Landing', 
    'FD PDP See Details', 
    'FD Share', 
    'FD View All', 
    'Coupon Tnc Clicked', 
    'Coupon View All',
    "Banner clicked", 
    "Charged", 
    "Product Added", 
    "PType Cat Clicked", 
    "Products Searched", 
    "App Uninstalled", 
    "App Launched", 
    "Primary Cat Clicked", 
    "Sub Cat Clicked", 
    "App Installed", 
    "Order Cancelled", 
    "Application Opened",
    "Null Search"
    ]

CLEVERTAP_CL_ACCOUNT_ID = "867-RZK-995Z"
CLEVERTAP_CL_PASSCODE = "SMQ-IOB-WXKL"

cl_app_event_names = [
    'Notification Clicked', 
    'Notification Delivered', 
    'Notification Replied', 
    'Notification Viewed', 
    'UTM Visited  Address not serviceable', 
    'Address Submit', 
    'App Launched Custom', 
    'Apply Coupon', 
    'Bottom Tab', 
    'Checkout Started', 
    'Coupon Applied', 
    'Coupon Selected', 
    'Cx Referral', 
    'Cx Referral Landing', 
    'GB Charged', 
    'GB Product Added', 
    'GB Share', 
    'List Share', 
    'List Viewed Cat Nav', 
    'Product Clicked', 
    'Product List Viewed', 
    'Product Share', 
    'Successful Registration', 
    'Successful Login  WA Status Banner Click  WA Status Save Number', 
    'WA Status Success', 
    'Session Concluded', 
    'Payment Mode Selected', 
    'KJ Landing', 
    'KJ Spin Clicked', 
    'KJ Past SC Landing', 
    'KJ Past SC Clicked', 
    'KJ SC Landing', 
    'KJ Scratched', 
    'Story Clicked', 
    'Story Viewed', 
    'KJ SC Coupon_Copy', 
    'Story Shared', 
    'FD PDU Clicked', 
    'FD PDP Landing', 
    'FD PDP See Details', 
    'FD Share', 
    'FD View All', 
    'Coupon Tnc Clicked', 
    'Coupon View All',
    "Banner clicked", 
    "Charged", 
    "Product Added", 
    "PType Cat Clicked", 
    "Products Searched", 
    "App Uninstalled", 
    "App Launched", 
    "Primary Cat Clicked", 
    "Sub Cat Clicked", 
    "App Installed", 
    "Order Cancelled", 
    "Application Opened",
    "Null Search",
    "Banner share",
    "My Order Share Order",
    "Video Played",
    "Place Order Clicked",
    "Shop Share",
    "Cx Page Banner Clicked"
    ]




CLEVERTAP_CX_ACCOUNT_ID = "4RW-KZK-995Z"
CLEVERTAP_CX_PASSCODE = "AOW-ROB-WXKL"

cx_web_event_names = [
    "Msite address form landing",
    "Msite address landing",
    "Msite address unavailable landing",
    "Msite already user landing",
    "Msite app install kare",
    "Msite charged",
    "msite confirm order",
    "Msite install clicked",
    "Msite invalid otp",
    "Msite landing",
    "msite location search",
    "Msite location submit",
    "Msite location user kare",
    "Msite number entered",
    "Msite number verified",
    "Msite order cancel",
    "Msite order failed",
    "Msite permission denied",
    "Msite permission granted",
    "Msite whatsapp unmark",
    "Msite cms item clicked"
    ]