import os
from dotenv import load_dotenv
load_dotenv()

mapping = {
    "source": {
        "source_type": "api",
        "db_name": "facebook_ads",
        "access_token": os.getenv("FACEBOOK_ADS_TOKEN_CX"),
        "app_secret": os.getenv("FACEBOOK_ADS_APP_SECRET_CX"),
        "ad_account_id": os.getenv("FACEBOOK_ADS_AD_ACCOUNT_ID_CX"),
        "app_id": os.getenv("FACEBOOK_ADS_APP_ID_CX")
    },
    "destination": {
        
        'redshift': {
            'host': os.getenv('REDSHIFT_URL'),
            'database': 'redshift-db-name',
            'user': os.getenv('REDSHIFT_USER'),
            'password': os.getenv('REDSHIFT_PASSWORD'),
            'schema': 'facebook_ads_cx_new',
            's3_bucket_name': 's3-bucket-name',
            'destination_type': 'redshift'
        },
        # 'ec_1': {
        #     "db_name": "database-name",
        #     "password": os.getenv('DB_PASSWORD'),
        #     "url": "destination.connection.url",
        #     "username": os.getenv('DB_USERNAME'),
        #     "schema": "public",
        #     'destination_type': 'pgsql'
        # },
        'ec_2':  {
            "db_name": "database-name",
            "password": os.getenv('DB_PASSWORD'),
            "url": "destination.connection.url",
            "username": os.getenv('DB_USERNAME'),
            "schema": "public",
            'destination_type': 'pgsql'
        },
        # 'destination_3': {
        #     "db_name": "database-name",
        #     "password": os.getenv('DB_PASSWORD'),
        #     "url": "destination.connection.url",
        #     "username": os.getenv('DB_USERNAME'),
        #     "destination_type": "pgsql",
        #     "schema": "public"
        # }

    },
    "apis": [
        {
            'api_name': 'ads_insights',
            'project_name': 'facebook_ads_cx_new',
            'start_day': '-1',
            'end_day': '-1',
            'slack_channel': 'C025PTAUUFP',
            'strict': True,
            'fields': {
                "__hevo__ingested_at": "int",
                "__hevo__loaded_at": "int",
                "__hevo_id": "str",
                "account_currency": "str",
                "account_id": "int",
                "account_name": "str",
                "actions_post_engagement_1d_view": "int",
                "actions_post_engagement_7d_click": "int",
                "actions_comment": "int",
                "actions_like": "int",
                "actions_link_click": "int",
                "actions_onsite_conversion_post_save": "int",
                "actions_page_engagement": "int",
                "actions_post": "int",
                "actions_post_engagement": "int",
                "actions_post_reaction": "int",
                "actions_video_view": "int",
                "ad_id": "int",
                "ad_name": "str",
                "adset_id": "int",
                "adset_name": "str",
                "buying_type": "str",
                "campaign_id": "int",
                "campaign_name": "str",
                "clicks": "int",
                "conversion_rate_ranking": "str",
                "cost_per_action_type_page_engagement_1d_view": "float",
                "cost_per_action_type_page_engagement_7d_click": "float",
                "cost_per_inline_link_click": "float",
                "cost_per_inline_post_engagement": "float",
                "cost_per_like": "float",
                "cost_per_action_type_link_click": "float",
                "cost_per_action_type_onsite_conversion_post_save": "float",
                "cost_per_outbound_click": "float",
                "cost_per_action_type_page_engagement": "float",
                "cost_per_action_type_post_engagement": "float",
                "cost_per_thruplay_video_view_1d_view": "float",
                "cost_per_thruplay_video_view_7d_click": "float",
                "cost_per_thruplay_video_view": "float",
                "cost_per_unique_1d_view": "float",
                "cost_per_unique_7d_click": "float",
                "cost_per_unique_click": "float",
                "cost_per_unique_inline_link_click": "float",
                "cost_per_unique_like": "float",
                "cost_per_unique_action_type_link_click": "float",
                "cost_per_unique_action_type_omni_activate_app": "float",
                "cost_per_unique_action_type_omni_activate_app": "float",
                "cost_per_unique_action_type_omni_app_install": "float",
                "cost_per_unique_omni_complete_registration": "float",
                "cost_per_unique_action_type_omni_custom": "float",
                "cost_per_unique_action_type_omni_purchase": "float",
                "cost_per_unique_action_type_omni_view_content": "float",
                "cost_per_unique_action_type_onsite_conversion_post_save": "float",
                "cost_per_unique_outbound_click": "float",
                "cost_per_unique_action_type_page_engagement": "float",
                "cost_per_unique_action_type_post_engagement": "float",
                "cost_per_unique_action_type_video_view": "float",
                "cost_per_action_type_video_view": "float",
                "cpc": "float",
                "cpm": "float",
                "cpp": "float",
                "ctr": "float",
                "date_start": "datetime",
                "date_stop": "datetime",
                "engagement_rate_ranking": "str",
                "frequency": "float",
                "impressions": "int",
                "inline_link_click_ctr": "float",
                "inline_link_clicks": "int",
                "inline_post_engagement": "int",
                "instant_experience_clicks_to_open": "int",
                "instant_experience_clicks_to_start": "int",
                "objective": "str",
                "optimization_goal": "str",
                "outbound_clicks": "int",
                "outbound_clicks_ctr": "float",
                "quality_ranking": "str",
                "reach": "int",
                "social_spend": "float",
                "spend": "float",
                "unique_actions_1d_view": "int",
                "unique_actions_7d_click": "int",
                "unique_actions_app_custom_event": "int",
                "unique_actions_app_custom_event_fb_mobile_activate_app": "int",
                "unique_actions_app_custom_event_fb_mobile_add_to_cart": "int",
                "unique_actions_app_custom_event_fb_mobile_complete_registration": "int",
                "unique_actions_app_custom_event_fb_mobile_content_view": "int",
                "unique_actions_app_custom_event_fb_mobile_purchase": "int",
                "unique_actions_app_custom_event_other": "int",
                "unique_actions_comment": "int",
                "unique_actions_like": "int",
                "unique_actions_link_click": "int",
                "unique_actions_mobile_app_install": "int",
                "unique_actions_omni_activate_app": "int",
                "unique_actions_omni_add_to_cart": "int",
                "unique_actions_omni_app_install": "int",
                "unique_actions_omni_complete_registration": "int",
                "unique_actions_omni_custom": "int",
                "unique_actions_omni_purchase": "int",
                "unique_actions_omni_view_content": "int",
                "unique_actions_onsite_conversion_post_save": "int",
                "unique_actions_page_engagement": "int",
                "unique_actions_post": "int",
                "unique_actions_post_engagement": "int",
                "unique_actions_post_reaction": "int",
                "unique_actions_video_view": "int",
                "unique_clicks": "int",
                "unique_ctr": "float",
                "unique_inline_link_click_ctr": "float",
                "unique_inline_link_clicks": "int",
                "unique_link_clicks_ctr": "float",
                "unique_outbound_clicks_outbound_click": "int",
                "unique_outbound_clicks_ctr_outbound_click": "float",
                "video_30_sec_watched_actions_video_view_1d_view": "int",
                "video_30_sec_watched_actions_video_view_7d_click": "int",
                "video_30_sec_watched_actions_video_view": "int",
                "video_avg_time_watched_actions_video_view": "int",
                "video_p100_watched_actions_video_view": "int",
                "video_p25_watched_actions_video_view": "int",
                "video_p50_watched_actions_video_view": "int",
                "video_p75_watched_actions_video_view": "int",
                "video_p95_watched_actions_video_view": "int",
                "video_play_actions_video_view_1d_view": "int",
                "video_play_actions_video_view_7d_click": "int",
                "video_play_actions_video_view": "int",
                "video_play_curve_actions_video_view": "str",
                "video_thruplay_watched_actions_video_view_1d_view": "int",
                "video_thruplay_watched_actions_video_view_7d_click": "int",
                "video_thruplay_watched_actions_video_view": "int",
                "website_ctr_link_click": "float"
            },
            'primary_keys': ["__hevo_id"],
            'lob_fields': {
            },

            'api_to_field_mapping': {
                "account_currency": "account_currency",
                "account_id": "account_id",
                "account_name": "account_name",
                "actions_page_engagement_1d_view": "actions_page_engagement_1d_view",
                "actions_page_engagement_7d_click": "actions_page_engagement_7d_click",
                "actions_comment": "actions_comment",
                "actions_like": "actions_like",
                "actions_link_click": "actions_link_click",
                "actions_onsite_conversion_post_save": "actions_onsite_conversion_post_save",
                "actions_page_engagement": "actions_page_engagement",
                "actions_post": "actions_post",
                "actions_post_engagement": "actions_post_engagement",
                "actions_post_reaction": "actions_post_reaction",
                "actions_video_view": "actions_video_view",
                "ad_id": "ad_id",
                "ad_name": "ad_name",
                "adset_id": "adset_id",
                "adset_name": "adset_name",
                "buying_type": "buying_type",
                "campaign_id": "campaign_id",
                "campaign_name": "campaign_name",
                "clicks": "clicks",
                "conversion_rate_ranking": "conversion_rate_ranking",
                "cost_per_action_type_page_engagement_1d_view": "cost_per_action_type_page_engagement_1d_view",
                "cost_per_action_type_page_engagement_7d_click": "cost_per_action_type_page_engagement_7d_click",
                "cost_per_inline_link_click": "cost_per_inline_link_click",
                "cost_per_inline_post_engagement": "cost_per_inline_post_engagement",
                "cost_per_like": "cost_per_like",
                "cost_per_action_type_link_click": "cost_per_action_type_link_click",
                "cost_per_action_type_onsite_conversion_post_save": "cost_per_action_type_onsite_conversion_post_save",
                "cost_per_outbound_click": "cost_per_outbound_click",
                "cost_per_action_type_page_engagement": "cost_per_action_type_page_engagement",
                "cost_per_action_type_post_engagement": "cost_per_action_type_post_engagement",
                "cost_per_thruplay_video_view_1d_view": "cost_per_thruplay_video_view_1d_view",
                "cost_per_thruplay_video_view_7d_click": "cost_per_thruplay_video_view_7d_click",
                "cost_per_thruplay_video_view": "cost_per_thruplay_video_view",
                "cost_per_unique_1d_view": "cost_per_unique_1d_view",
                "cost_per_unique_7d_click": "cost_per_unique_7d_click",
                "cost_per_unique_click": "cost_per_unique_click",
                "cost_per_unique_inline_link_click": "cost_per_unique_inline_link_click",
                "cost_per_unique_like": "cost_per_unique_like",
                "cost_per_unique_action_type_link_click": "cost_per_unique_action_type_link_click",
                "cost_per_unique_action_type_omni_activate_app": "cost_per_unique_action_type_omni_activate_app",
                "cost_per_unique_action_type_omni_add_to_cart": "cost_per_unique_action_type_omni_add_to_cart",
                "cost_per_unique_action_type_omni_app_install": "cost_per_unique_action_type_omni_app_install",
                "cost_per_unique_omni_complete_registration": "cost_per_unique_omni_complete_registration",
                "cost_per_unique_action_type_omni_custom": "cost_per_unique_action_type_omni_custom",
                "cost_per_unique_action_type_omni_purchase": "cost_per_unique_action_type_omni_purchase",
                "cost_per_unique_action_type_omni_view_content": "cost_per_unique_action_type_omni_view_content",
                "cost_per_unique_action_type_onsite_conversion_post_save": "cost_per_unique_action_type_onsite_conversion_post_save",
                "cost_per_unique_outbound_click": "cost_per_unique_outbound_click",
                "cost_per_unique_action_type_page_engagement": "cost_per_unique_action_type_page_engagement",
                "cost_per_unique_action_type_post_engagement": "cost_per_unique_action_type_post_engagement",
                "cost_per_unique_action_type_video_view": "cost_per_unique_action_type_video_view",
                "cost_per_action_type_video_view": "cost_per_action_type_video_view",
                "cpc": "cpc",
                "cpm": "cpm",
                "cpp": "cpp",
                "ctr": "ctr",
                "date_start": "date_start",
                "date_stop": "date_stop",
                "engagement_rate_ranking": "engagement_rate_ranking",
                "frequency": "frequency",
                "impressions": "impressions",
                "inline_link_click_ctr": "inline_link_click_ctr",
                "inline_link_clicks": "inline_link_clicks",
                "inline_post_engagement": "inline_post_engagement",
                "instant_experience_clicks_to_open": "instant_experience_clicks_to_open",
                "instant_experience_clicks_to_start": "instant_experience_clicks_to_start",
                "objective": "objective",
                "optimization_goal": "optimization_goal",
                "outbound_clicks": "outbound_clicks",
                "outbound_clicks_ctr": "outbound_clicks_ctr",
                "quality_ranking": "quality_ranking",
                "reach": "reach",
                "social_spend": "social_spend",
                "spend": "spend",
                # "unique_actions_1d_view": "unique_actions",
                # "unique_actions_7d_click": "unique_actions",
                "unique_actions_app_custom_event": "unique_actions_app_custom_event",
                "unique_actions_app_custom_event_fb_mobile_activate_app": "unique_actions_app_custom_event_fb_mobile_activate_app",
                "unique_actions_app_custom_event_fb_mobile_add_to_cart": "unique_actions_app_custom_event_fb_mobile_add_to_cart",
                "unique_actions_app_custom_event_fb_mobile_complete_registration": "unique_actions_app_custom_event_fb_mobile_complete_registration",
                "unique_actions_app_custom_event_fb_mobile_content_view": "unique_actions_app_custom_event_fb_mobile_content_view",
                "unique_actions_app_custom_event_fb_mobile_purchase": "unique_actions_app_custom_event_fb_mobile_purchase",
                "unique_actions_app_custom_event_other": "unique_actions_app_custom_event_other",
                "unique_actions_comment": "unique_actions_comment",
                "unique_actions_like": "unique_actions_like",
                "unique_actions_link_click": "unique_actions_link_click",
                "unique_actions_mobile_app_install": "unique_actions_mobile_app_install",
                "unique_actions_omni_activate_app": "unique_actions_omni_activate_app",
                "unique_actions_omni_add_to_cart": "unique_actions_omni_add_to_cart",
                "unique_actions_omni_app_install": "unique_actions_omni_app_install",
                "unique_actions_omni_complete_registration": "unique_actions_omni_complete_registration",
                "unique_actions_omni_custom": "unique_actions_omni_custom",
                "unique_actions_omni_purchase": "unique_actions_omni_purchase",
                "unique_actions_omni_view_content": "unique_actions_omni_view_content",
                "unique_actions_onsite_conversion_post_save": "unique_actions_onsite_conversion_post_save",
                "unique_actions_page_engagement": "unique_actions_page_engagement",
                "unique_actions_post": "unique_actions_post",
                "unique_actions_post_engagement": "unique_actions_post_engagement",
                "unique_actions_post_reaction": "unique_actions_post_reaction",
                "unique_actions_video_view": "unique_actions_video_view",
                "unique_clicks": "unique_clicks",
                "unique_ctr": "unique_ctr",
                "unique_inline_link_click_ctr": "unique_inline_link_click_ctr",
                "unique_inline_link_clicks": "unique_inline_link_clicks",
                "unique_link_clicks_ctr": "unique_link_clicks_ctr",
                "unique_outbound_clicks_outbound_click": "unique_outbound_clicks_outbound_click",
                "unique_outbound_clicks_ctr_outbound_click": "unique_outbound_clicks_ctr_outbound_click",
                "video_30_sec_watched_actions_video_view_1d_view": "video_30_sec_watched_actions_video_view_1d_view",
                "video_30_sec_watched_actions_video_view_7d_click": "video_30_sec_watched_actions_video_view_7d_click",
                "video_30_sec_watched_actions_video_view": "video_30_sec_watched_actions_video_view",
                "video_avg_time_watched_actions_video_view": "video_avg_time_watched_actions_video_view",
                "video_p100_watched_actions_video_view": "video_p100_watched_actions_video_view",
                "video_p25_watched_actions_video_view": "video_p25_watched_actions_video_view",
                "video_p50_watched_actions_video_view": "video_p50_watched_actions_video_view",
                "video_p75_watched_actions_video_view": "video_p75_watched_actions_video_view",
                "video_p95_watched_actions_video_view": "video_p95_watched_actions_video_view",
                "video_play_actions_video_view_1d_view": "video_play_actions_video_view_1d_view",
                "video_play_actions_video_view_7d_click": "video_play_actions_video_view_7d_click",
                "video_play_actions_video_view": "video_play_actions_video_view",
                "video_play_curve_actions_video_view": "video_play_curve_actions_video_view",
                "video_thruplay_watched_actions_video_view_1d_view": "video_thruplay_watched_actions_video_view_1d_view",
                "video_thruplay_watched_actions_video_view_7d_click": "video_thruplay_watched_actions_video_view_7d_click",
                "video_thruplay_watched_actions_video_view": "video_thruplay_watched_actions_video_view",
                "website_ctr_link_click": "website_ctr_link_click"
            },
            'date_column': 'date_stop',
            'cron': 'self-managed',
        },

        {
            'api_name': 'ads_campaigns',
            'project_name': 'facebook_ads_cx_new',
            'start_day': '-1',
            'end_day': '-1',
            'slack_channel': 'C025PTAUUFP',
            'strict': True,
            'fields': {
                'account_id': 'int',
                'budget_rebalance_flag': 'bool',
                'budget_remaining': 'int',
                'buying_type': 'str',
                'can_create_brand_lift_study': 'bool',
                'can_use_spend_cap': 'bool',
                'configured_status': 'str',
                'created_time': 'datetime',
                'effective_status': 'str',
                'id': 'int',
                'is_skadnetwork_attribution': 'bool',
                'name': 'str',
                'objective': 'str',
                'smart_promotion_type': 'str',
                'source_campaign_id': 'int',
                'special_ad_category': 'str',
                'spend_cap': 'int',
                'start_time': 'datetime',
                'status': 'str',
                'topline_id': 'int',
                'updated_time': 'datetime'
            },
            'primary_keys': ["id"],
            'lob_fields': {},
            'api_to_field_mapping': {
                'account_id': 'account_id',
                'budget_rebalance_flag': 'budget_rebalance_flag',
                'budget_remaining': 'budget_remaining',
                'buying_type': 'buying_type',
                'can_create_brand_lift_study': 'can_create_brand_lift_study',
                'can_use_spend_cap': 'can_use_spend_cap',
                'configured_status': 'configured_status',
                'created_time': 'created_time',
                'effective_status': 'effective_status',
                'id': 'id',
                'is_skadnetwork_attribution': 'is_skadnetwork_attribution',
                'name': 'name',
                'objective': 'objective',
                'smart_promotion_type': 'smart_promotion_type',
                'source_campaign_id': 'source_campaign_id',
                'special_ad_category': 'special_ad_category',
                'spend_cap': 'spend_cap',
                'start_time': 'start_time',
                'status': 'status',
                'topline_id': 'topline_id',
                'updated_time': 'updated_time'
            },
            'cron': 'self-managed'
        }
    ]
}
