mapping = {
    'source': {
        'source_type': 'sql',
        'url': 'cmdb-rr.cbo3ijdmzhje.ap-south-1.rds.amazonaws.com',
        'db_name': 'cmdb',
        'username': 'saksham_garg',
        'password': '3y5HMs^2qy%&Kma'
    },
    'destination': {
        'destination_type': 'pgsql',
        'url': '65.0.105.34',
        'db_name': 'dms',
        'username': 'saksham_garg',
        'password': '3y5HMs^2qy%&Kma'
    },
    'tables': [
        {
            'table_name': 'team_leaders',
            'cron': 'self-managed',
            'mode': 'syncing',
            'primary_key': 'user_id',
            'primary_key_datatype': 'int',
            'bookmark': 'updated_at',
            'improper_bookmarks': False,
            'batch_size': 10000,
            'lob_fields_length': {
                'tracking_info': 65535,

                'description': 4048,
                'source': 4048,
                'availability_hours': 4048,
                'family_income': 4048,
                'advertising_set_id': 4048,
                'advertising_set_name': 4048,
                'advertising_campaign_id': 1024,
                'advertising_objective_name': 4048,
                'advertising_id': 4048,
                'sign_up_code': 4048,
                'age': 4048,
                'gender': 4048,
                'vehicle': 4048,
                'forced_catalogue_name': 4048,
                'in_area_of_exclusive_cl_id': 4048,
                'marketing_link': 4048,
                'position': 4048,
                'sub_position': 4048,
                'leader_state': 4048,
                'url': 10240,
                'name': 4048,
                'phone_number': 4048,
                'leader_id': 4048,
                'route': 4048,
                'ifsc_code': 4048,
                'account_number': 4048,
                'bank_name': 4048,
                'leader_unique_id': 4048,
                'app_share_link': 4048,
                'account_holder_name': 4048,
                'remarks': 4048,
                'category': 4048,
                'occupation': 4048,
                'refer_cl_link': 4048,
                'micromarket': 4048,
                'alternate_phone': 4048,
                'user_image': 4048,
                'one_signal_user_id': 4048,
                'discarded_reason': 4048,
                'install_google_ad_campaign': 4048,
                'leadsquared_id': 4048,
                'quartile': 4048,
                'bd_phone_number': 4048,
                'advertising_partner': 4048,
                'advertising_campaign': 4048,
                'no_of_family_members': 4048,
                'income': 4048,
                'grocery_spending': 4048,
                'pancard_number': 4048,
                'version_code': 4048,
                'version_name': 4048,
                'first_version_code': 4048,
                'first_version_name': 4048,
                'pancard_name': 4048,
                'codepush_version': 4048,
                'cover_image': 4048,
                'cover_text': 4048,
                'approved_by': 4048,
                'suspension_reason': 4048,
                'martial_status': 4048,
                'leader_shop': 4048,
                'joining_reason': 4048,
                'id': 4048,
            },
            'buffer_updation_lag':{
                'hours': 2,
            },
            'grace_updation_lag': {
                'hours': 2
            },
        },
    ]
}